name: Flutter CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        flutter-channel: [ 'stable' ]

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter-channel }}

      - name: Print Dart SDK version
        run: dart --version

      - name: Print Flutter SDK version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Format code
        if: ${{ matrix.flutter-channel == 'stable' }}
        run: dart format lib --set-exit-if-changed

      - name: Analyze
        if: ${{ matrix.flutter-channel == 'stable' }}
        run: dart analyze lib; flutter analyze

      - name: Build Debug APK
        run: flutter build apk --debug --no-shrink